# Generated by Django 5.2.13 on 2026-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbs', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online/SSLCommerz'), ('Cash', 'Cash/Manual')], default='Online', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('Full', 'Full Payment (100%)'), ('Partial', 'Partial Payment (50%)')], default='Full', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='ssl_tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='total_inventory',
            field=models.IntegerField(default=5, help_text='এই টাইপের মোট কয়টি রুম হোটেলে আছে'),
        ),
    ]
